apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic-app
  labels:
    app: spring-petclinic-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-petclinic-app
  template:
    metadata:
      labels:
        app: spring-petclinic-app
    spec:
      containers:
        - name: spring-petclinic-app
          image: explaincs/spring-petclinic:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8088

---
apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8088
      protocol: TCP
  selector:
    app: spring-petclinic-app
